apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web:8080/api_jsonrpc.php
    isDefault: true
    jsonData:
      # Creds
      username: Admin
      password: zabbix
      # Trends
      trends: true
      trendsFrom: "7d"
      trendsRange: "4d"
      cacheTTL: "1h"
      # Alerting
      alerting: true
      addThresholds: false
      alertingMinSeverity: 3
      disableReadOnlyUsersAck: false
      dbConnectionEnable: false
    version: 1
    editable: false
    
  - name: MySQL Zabbix
    type: mysql
    url: mysql-server:3306
    database: zabbix
    user: root
#    password: "S3cret"
    secureJsonData:
      password: "S3cret2022"
    #    jsonData:
    #      sslmode: "enable"
    #      maxOpenConns: 200
    #      maxIdleConns: 10
    #      connMaxLifetime: 14400
    #      postgresVersion: 1200
    #      timescaledb: false
